### ISSUE TITLE
Improved debug on migrations

### ISSUE THREAD

**Issue by pdbossman** [scylladb/scylla-migrator#181]
There are different mandatory and optional input parameters to a scylla migration.

It would be useful at the beginning of migration to dump out input parameters and actual parameters used.
For example, aws region for DynamoDB, scanSegments.

Right now, it is guess work what these parameters are and if they were visible, the diagnosis of problems would be much faster.

**Comment by julienrf** [comment]
I reviewed the way we use the configuration parameters and discovered that some of them are ineffective (e.g., setting `scanSegments` _in the `target`_ does nothing, it works only if set to the `source` table).

Other than that, there are already logs that describe which parameters are used to configure the Hadoop job properties. See e.g. [these logs](https://github.com/scylladb/scylla-migrator/actions/runs/10385678098/job/28755344840#step:7:259) or [these logs](https://github.com/scylladb/scylla-migrator/actions/runs/10385678098/job/28755344840#step:7:799).

@pdbossman would you consider this issue fixed with the following plan?
- Remove the unused configuration parameters, which currently contribute to your confusion,
- Add more logs about characteristics of the migration that come from the config vs characteristics that are computed with default values (e.g [here](https://github.com/scylladb/scylla-migrator/blob/b9be9fb684fb0e51bf7c8cbad79a1f42c6689103/migrator/src/main/scala/com/scylladb/migrator/DynamoUtils.scala#L220) the supplied AWS region is used)

**Comment by julienrf** [comment]
See PR #199.
